### ISSUE TITLE
Category 컴포넌트 구현

### ISSUE THREAD

**Issue by Jeong-Taeho** [prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE#56]
## 구현내용
- 카테고리 아이콘이 모여있는 컴포넌트를 구현합니다.

## 세부사항
![image](https://github.com/prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE/assets/117630589/b294ae90-c74b-43e6-8f1e-8468c824556b)

## 기타

가로 스크롤을 적용할 예정인데 저한테는 어려울 것 같아서 모르면 많이 물어보겠습니다..😂

**Comment by jkea1** [comment]
빅 티켓에도 적어주셨으면 합니다!
